### ISSUE TITLE
[GDPR] Question about sdk

### ISSUE THREAD

**Issue by AbreuY** [MFlisar/MaterialDialogs#4]
GDPR dialog does it work independently, or is it connected with the google UMP SDK to obtain consent?

`implementation 'com.google.android.ump:user-messaging-platform:2.0.0'`

**Comment by MFlisar** [comment]
I've no idea why a dialog should depend on messaging, but please, just check it yourself:

https://github.com/MFlisar/MaterialDialogs/blob/43fc1279039933c0943ea7f4c3516358cfaeccae/dialogs/gdpr/build.gradle.kts#L45-L67

https://github.com/MFlisar/MaterialDialogs/blob/43fc1279039933c0943ea7f4c3516358cfaeccae/core/build.gradle.kts#L45-L68
